# version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile.gcloud
    container_name: portfolist-web
    ports:
      - "3000:3000"
    env_file:
      - ../.env
    restart: unless-stopped
    # tailscale tuning, for inline - docker run - below
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun

# docker run -d \
#   --name=portfolist-web \
#   --cap-add=NET_ADMIN \
#   --device=/dev/net/tun:/dev/net/tun \
#   -p 3000:3000 \
