FROM node:26-alpine
ENV TAILSCALE_AUTHKEY="tskey-auth-123456"

RUN apk add --no-cache curl ca-certificates iptables ip6tables python3 make g++ tailscale

# Set up your Node app
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm i 
COPY . .
RUN npm run build

COPY docker/start.sh .
RUN chmod +x start.sh

EXPOSE $PORT

CMD ["./start.sh", "all"]
